# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bef6d856fb650038b8191a07b2d57340c3c471f68bde81ab08c60ccbe4a451e69fc5661c34dc6919af6e3ed1bc47c871838c0452dc97c717a3d75ebabf8015f

test:
  secret_key_base: b3ff8bff4b07fa907ee7eeecb42f8edefa79f01d0c5d0c798d08c9b64a1f0730f0d7f8efc7ecb31e36af570ad16f63236abc759f0f0785158f1f64a41e97caf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
